[package]
name = "pwshac"
version = "1.0.1"
edition = "2024"
description = "Prints PowerShell Remove-Alias commands while preserving selected aliases"
readme = "README.md"
repository = "https://github.com/NazmusSayad/pwshac"
homepage = "https://github.com/NazmusSayad/pwshac"
license = "MIT"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
